# Generated by Django 2.1.5 on 2019-02-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20190212_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.CharField(max_length=500),
        ),
    ]
