# Generated by Django 2.1.5 on 2019-02-19 01:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pugorugh', '0003_auto_20190212_2050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdog',
            unique_together={('user', 'dog')},
        ),
    ]
